# Generated by Django 5.2.7 on 2025-10-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfmodule',
            name='file',
            field=models.FileField(upload_to='course_pdfs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
